### ISSUE TITLE
vdso failed to compile when building enarx-keepldr

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx-keepldr#10]
HW: NUC7JY
SW: Fedora 32
Patch: https://download.copr.fedorainfracloud.org/results/npmccallum/enarx/fedora-32-x86_64/01632008-kernel/

Following https://github.com/enarx/enarx-keepldr
When **$cargo +nightly build**, error occurred as below:

warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.11.5` within 30s)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.11.5` within 30s)
error: failed to download from `https://crates.io/api/v1/crates/x86_64/0.11.5/download`

Caused by:
  [28] Timeout was reached (failed to download any data for `x86_64 v0.11.5` within 30s)
error: failed to run custom build command for `enarx-keepldr v0.1.0 (/home/sgx/enarx-keepldr)`

Caused by:
  process didn't exit successfully: `/home/sgx/enarx-keepldr/target/debug/build/enarx-keepldr-0f502a033f9ca075/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=PROFILE
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  cargo:rerun-if-changed=internal/shim-sev/Cargo.tml
  cargo:rerun-if-changed=internal/shim-sev/Cargo.toml
  cargo:rerun-if-changed=internal/shim-sev/Cargo.lock
  cargo:rerun-if-changed=internal/shim-sev/link.json
  cargo:rerun-if-changed=internal/shim-sev/.cargo/config
  cargo:rerun-if-changed=internal/shim-sev/build.rs
  cargo:rerun-if-changed=internal/shim-sev/src/payload.rs
  cargo:rerun-if-changed=internal/shim-sev/src/addr.rs
  cargo:rerun-if-changed=internal/shim-sev/src/asm.rs
  cargo:rerun-if-changed=internal/shim-sev/src/main.rs
  cargo:rerun-if-changed=internal/shim-sev/src/no_std.rs
  cargo:rerun-if-changed=internal/shim-sev/src/paging.rs
  cargo:rerun-if-changed=internal/shim-sev/src/hostlib.rs
  cargo:rerun-if-changed=internal/shim-sev/src/syscall.rs
  cargo:rerun-if-changed=internal/shim-sev/src/hostcall.rs
  cargo:rerun-if-changed=internal/shim-sev/src/gdt.rs
  cargo:rerun-if-changed=internal/shim-sev/src/usermode.rs
  cargo:rerun-if-changed=internal/shim-sev/src/start.S
  cargo:rerun-if-changed=internal/shim-sev/src/random.rs
  cargo:rerun-if-changed=internal/shim-sev/src/frame_allocator.rs
  cargo:rerun-if-changed=internal/shim-sev/src/shim_stack.rs
  cargo:rerun-if-changed=internal/shim-sev/src/print.rs

  --- stderr
  Failed to build shim internal/shim-sev

**Comment by xiaonan-INTC** [comment]
On Ubuntu 18.04,  another error occurred:

   Compiling enarx-keepldr v0.1.0 (/home/sgx/enarx-keepldr)
error: failed to run custom build command for `enarx-keepldr v0.1.0 (/home/sgx/enarx-keepldr)`

Caused by:
  process didn't exit successfully: `/home/sgx/enarx-keepldr/target/debug/build/enarx-keepldr-0f502a033f9ca075/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=PROFILE
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled

  --- stderr
  cc: error: unrecognized command line option ‘-static-pie’; did you mean ‘-static’?
  thread 'main' panicked at 'Failed to compile "/home/sgx/enarx-keepldr/tests/bin/write_emsgsize.c"', build.rs:64:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

Does there have any other settings of Enarx development environment?

**Comment by haraldh** [comment]
> HW: NUC7JY
> SW: Fedora 32
> Patch: https://download.copr.fedorainfracloud.org/results/npmccallum/enarx/fedora-32-x86_64/01632008-kernel/
> 
> Following https://github.com/enarx/enarx-keepldr
> When **$cargo +nightly build**, error occurred as below:
> 
> warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.11.5` within 30s)
> warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.11.5` within 30s)
> error: failed to download from `https://crates.io/api/v1/crates/x86_64/0.11.5/download`

Oh, with the fedora rust build system, this is a little bit tricky, because it uses `build.rs` to build additional internal crates found in the `internal/` sub directory. A packager has to make sure, that:
1. `internal/*` has `.cargo/config` patched with whatever is needed in the build system
2.  All dependencies of `internal/*/Cargo.toml` can be downloaded

**Comment by haraldh** [comment]
> --- stderr
> cc: error: unrecognized command line option ‘-static-pie’; did you mean ‘-static’?

This version of ubuntu is too old. `gcc` does not yet understand `-static-pie`

**Comment by xiaonan-INTC** [comment]
> > --- stderr
> > cc: error: unrecognized command line option ‘-static-pie’; did you mean ‘-static’?
> 
> This version of ubuntu is too old. `gcc` does not yet understand `-static-pie`

Thanks, @haraldh, this error disappeared after upgrading gcc, :)

**Comment by xiaonan-INTC** [comment]
> > HW: NUC7JY
> > SW: Fedora 32
> > Patch: https://download.copr.fedorainfracloud.org/results/npmccallum/enarx/fedora-32-x86_64/01632008-kernel/
> > Following https://github.com/enarx/enarx-keepldr
> > When **$cargo +nightly build**, error occurred as below:
> > warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.11.5` within 30s)
> > warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.11.5` within 30s)
> > error: failed to download from `https://crates.io/api/v1/crates/x86_64/0.11.5/download`
> 
> Oh, with the fedora rust build system, this is a little bit tricky, because it uses `build.rs` to build additional internal crates found in the `internal/` sub directory. A packager has to make sure, that:
> 
> 1. `internal/*` has `.cargo/config` patched with whatever is needed in the build system
> 2. All dependencies of `internal/*/Cargo.toml` can be downloaded

@haraldh 
Some questions about your guidance:

Oh, with the fedora rust build system, this is a little bit tricky, because it uses build.rs to build additional internal crates found in the internal/ sub directory. 
**>> I tried Ubuntu 18.04, the same error occurred as Fedora 32. Both on Fedora 32 & Ubuntu 18.04, I just followed what the wiki instructed: Install Dependencies - Install Rust, Nightly and the MUSL target - Build, are there any other settings need to do?**

A packager has to make sure, that:
1. internal/* has .cargo/config patched with whatever is needed in the build system
**>>in internal/*, there are 2 folders shim-sev & shim-sgx, and both have .cargo/config, do I need some modification of .cargo/config? patched with whatever is needed in the build system means what to do?**

2. All dependencies of internal/*/Cargo.toml can be downloaded
**>>do you mean that for all internal/*/Cargo.toml, following part must be downloaded when run $cargo +nightly build
[dependencies]
sallyport = { path = "../../internal/sallyport", default-features = false }
sgx = { git = "https://github.com/enarx/sgx", rev = "512e077" }
rcrt1 = { path = "../../internal/rcrt1" }
goblin = { version = "0.2", default-features = false, features = [ "elf64" ] }
crt0stack = { version = "0.1", default-features = false }
libc = { version = "0.2", default-features = false }
primordial = "0.1"
nbytes = "0.1"
lset = "0.1"
how can I know which of the dependencies is not downloaded?
**

**Comment by haraldh** [comment]
>  how can I know which of the dependencies is not downloaded?

@xiaonan-INTC all deps without `path` will be downloaded.

**Comment by xiaonan-INTC** [comment]
> > how can I know which of the dependencies is not downloaded?
> 
> @xiaonan-INTC all deps without `path` will be downloaded.

thanks @haraldh 
Still not very clear with your guidance:

[haraldh ] Oh, with the fedora rust build system, this is a little bit tricky, because it uses build.rs to build additional internal crates found in the internal/ sub directory.
[xiaonan-INTC]
I tried Ubuntu 18.04, the same error occurred as Fedora 32. 
Both on Fedora 32 & Ubuntu 18.04, I just followed what the wiki instructed: Install Dependencies - Install Rust, Nightly and the MUSL target - Build, are there any other settings need to do? 
So build.rs in internal/ need to do some modification, not using default setting?

[haraldh ] A packager has to make sure, that:
internal/* has .cargo/config patched with whatever is needed in the build system
[xiaonan-INTC]
In internal/*, there are 2 folders shim-sev & shim-sgx both have .cargo/config, do I need some modification of .cargo/config? 
Patched with whatever is needed in the build system means to do what?

[haraldh ] All dependencies of internal/*/Cargo.toml can be downloaded
[xiaonan-INTC]
Do you mean that for all internal/*/Cargo.toml, [dependencies] part must be downloaded when run $cargo +nightly build?
How to check it?

**Comment by haraldh** [comment]
If I remember correctly, the crates needed to build a rust crate have to be converted to a rpm first, because they will be normal `BuildRequires` and not dynamically downloaded from `crates.io`.

**Comment by haraldh** [comment]
> For Fedora: If I remember correctly, the crates needed to build a rust crate have to be converted to a rpm first, because they will be normal `BuildRequires` and not dynamically downloaded from `crates.io`.

and yes, this is probably dependency hell for the maintainer

**Comment by haraldh** [comment]
Also, I don't think fedora supports rust nightly in its build system.

**Comment by haraldh** [comment]
In case you are **not** trying to make an rpm, your connection to `crates.io` seems to be flaky somehow.

**Comment by haraldh** [comment]
This URL works fine on my system: https://crates.io/api/v1/crates/x86_64/0.11.5/download

**Comment by haraldh** [comment]
Please re-open, if you think something is still not working.
