### ISSUE TITLE
Update README to better reflect minimum gcc version

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx-keepldr#106]
According to #102 , a minimum of gcc-9 with the backported `mtune=znver2` switch for musl-gcc is required on the system in order to run this code. It may be a good idea to include this in the README.

**Comment by haraldh** [comment]
We removed the option with https://github.com/enarx/enarx-keepldr/pull/104 which you reviewed and approved.

**Comment by lkatalin** [comment]
@haraldh Oh, I think I read it wrong. If all gcc versions are okay now then I can close this.

**Comment by haraldh** [comment]
I guess gcc 9 with static pie is still required

**Comment by lkatalin** [comment]
I think we probably should document that. Many people may have an older gcc.

**Comment by connorkuehl** [comment]
Closed by 6922c237b87b9dd517339aa7ce81dad375743fe2
