### ISSUE TITLE
Document memlock rlimit requirement for SEV-capable hosts

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx-keepldr#14]
The default maximum number of pinnable pages is 16 (at least it was on our Fedora box). A system administrator must configure this setting to be larger on a host where enarx-keepldr will be used with the SEV backend.

We configured ours with an entry under `/etc/security/limits.d/`:

`/etc/security/limits.d/sev.conf`:

```console
* - memlock 8388608
```

```console
$ man limits.conf
```

**Comment by npmccallum** [comment]
@dagrh This has implications for qemu too. Any suggestions on a default policy that works for everyone?

**Comment by dagrh** [comment]
@npmccallum I think libvirt normally sets the rlimit for us when the entry is set in the XML for the VM:

https://libvirt.org/kbase/launch_security_sev.html#memory
