### ISSUE TITLE
Fix the sallyport block size

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx-keepldr#23]
As a stopgap measure for hosting the wasmldr, we ended up increasing the size of the sallyport block by a large amount. This change must be effectively reverted immediately and implemented properly.

This PR merged the change: https://github.com/enarx/enarx-keepldr/pull/22

**Comment by haraldh** [comment]
@connorkuehl  @npmccallum why not make short reads instead? The rust implementation for `read_all()` just reads until `0` or an error occurred.

Alternatively we can do the same in our proxy `read()` in the shim and fill the buffer, until `0` or error.
