### ISSUE TITLE
Add integration tests for syscalls

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx-keepldr#260]
The following syscalls need integration tests:
* [ ] pipe
* [ ] fcntl with F_GETFD, F_SETFD, F_GETFL, F_SETFL
* [ ] ioctl with FIONBIO
* [ ] getsockname
* [ ] sendto
* [ ] setsockopt
* [ ] epoll_create1
* [ ] epoll_ctl
* [ ] epoll_wait
* [ ] getpid

**Comment by lkatalin** [comment]
@haraldh I've folded these into our master list of syscalls that need testing: https://github.com/enarx/enarx-keepldr/issues/9. Is it okay to close this issue?
