### ISSUE TITLE
Don't require setting `SEV_CHAIN` for the `sev` backend

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx-keepldr#64]
I think we should make the backends behave as similarly as possible. This means we should at least have a default for the `SEV_CHAIN` so that callers of `enarx-keepldr` don't have to special case on the backend where necessary.

**Comment by connorkuehl** [comment]
As of commit https://github.com/enarx/enarx-keepldr/commit/60220e3a48229a5a3b8d55227206f87489cdfe34, specifying `SEV_CHAIN` is not required as long as a valid certificate is found at one of the following paths:

1. The path pointed to at `SEV_CHAIN`
2. `$HOME/.cache/amd-sev/chain`
3. `/var/cache/amd-sev/chain`
