### ISSUE TITLE
Investigate deprecation warnings in Actions test workflows

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx-keepldr#83]
Our Actions test workflows seem to be producing warnings about deprecated functions. We should figure out what's going wrong and if we can fix it, or if this is an issue with Github.

**Comment by mbestavros** [comment]
The deprecation warnings link to [this blog post](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). They seem to happen on our `test` workflow -- a cursory glance reveals we do indeed make use of `set-env` to set up the SEV certificate chain in our workflow, though I can't find any mention of `add-path`. 

@connorkuehl or @haraldh Do either of you have any insight here? Github recommends moving to [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files) as an alternative; will that work for our cert chain setup process?

**Comment by connorkuehl** [comment]
@mbestavros Completing the work in this issue should allow us to remove the `set-env` logic entirely: https://github.com/enarx/sev/issues/25

**Comment by connorkuehl** [comment]
The `add-path` has been resolved upstream: https://github.com/actions-rs/toolchain/issues/124

The most recently linked pull request should resolve the other one.
